# Generated by Django 2.0.5 on 2018-06-03 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('srtp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProjectApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='标题')),
                ('ammountPeople', models.IntegerField(default=1, verbose_name='项目总人数')),
                ('guide_teacher', models.CharField(default='', max_length=10, verbose_name='指导老师')),
                ('info', models.TextField(default='', max_length=500, verbose_name='简介')),
                ('fileUpload', models.FileField(default='', upload_to='Issue_file/%Y/%m')),
                ('teacher_belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发布教师')),
            ],
        ),
    ]
