# Generated by Django 2.0.5 on 2018-06-03 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srtp', '0002_teacherprojectapply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherprojectapply',
            old_name='ammountPeople',
            new_name='amountPeople',
        ),
    ]
