# Generated by Django 2.0.5 on 2018-06-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srtp', '0003_auto_20180603_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcollectissue',
            name='to_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectcollectissue',
            name='to_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='teacherprojectapply',
            name='fileUpload',
            field=models.FileField(default='', upload_to='fileUpload/%Y/%m'),
        ),
    ]
