# Generated by Django 2.0.5 on 2018-06-14 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('srtp', '0004_auto_20180606_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectManageIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='标题')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='截止时间')),
                ('content', models.TextField(default='', max_length=500, verbose_name='发布内容')),
                ('publishTime', models.DateField(auto_now_add=True, verbose_name='发布时间')),
            ],
        ),
        migrations.CreateModel(
            name='SignUPGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountNumber', models.IntegerField(default=1, verbose_name='项目总人数')),
                ('signup_file', models.FileField(default='', upload_to='signup_file/%Y/%m')),
                ('verify_teacher', models.CharField(default='', max_length=10, verbose_name='教师审核意见')),
                ('verify_admin', models.CharField(default='', max_length=10, verbose_name='管理员审核意见')),
                ('medium_status', models.CharField(default='', max_length=10, verbose_name='中期文件提交状态')),
                ('final_status', models.CharField(default='', max_length=10, verbose_name='结题文件提交状态')),
                ('TPA_belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srtp.TeacherProjectApply', verbose_name='报名的项目')),
                ('apply_people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
        ),
        migrations.CreateModel(
            name='SignUpStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuID', models.CharField(default='', max_length=20, verbose_name='学号')),
                ('Class', models.CharField(default='', max_length=10, verbose_name='班级')),
                ('college', models.CharField(default='', max_length=20, verbose_name='学院')),
                ('realname', models.CharField(default='', max_length=10, verbose_name='真实姓名')),
                ('project_belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srtp.SignUPGroup', verbose_name='所属的报名组')),
            ],
        ),
        migrations.CreateModel(
            name='SubmitFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_file', models.FileField(default='', upload_to='medium_file/%Y/%m')),
                ('is_medium', models.BooleanField(default=False)),
                ('is_final', models.BooleanField(default=False)),
                ('SUG_belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srtp.SignUPGroup', verbose_name='所属组')),
            ],
        ),
    ]
