# Generated by Django 2.0.5 on 2018-06-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srtp', '0005_projectmanageissue_signupgroup_signupstudent_submitfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmanageissue',
            name='attribute',
            field=models.CharField(default='', max_length=5, verbose_name='通告属性'),
        ),
    ]
