# Generated by Django 2.0.5 on 2018-06-15 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srtp', '0006_projectmanageissue_attribute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmanageissue',
            old_name='attribute',
            new_name='kind',
        ),
    ]
