# Generated by Django 2.0.5 on 2018-06-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srtp', '0007_auto_20180615_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcollectissue',
            name='noticeType',
            field=models.CharField(default='srtp', max_length=10, verbose_name='通知类型'),
        ),
    ]
