# Generated by Django 2.0.5 on 2018-06-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srtp', '0008_projectcollectissue_noticetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmanageissue',
            name='noticeType',
            field=models.CharField(default='srtp_process', max_length=20, verbose_name='通知类型'),
        ),
    ]
