# Generated by Django 2.0.5 on 2018-05-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='phonenumber',
        ),
        migrations.AddField(
            model_name='student',
            name='college',
            field=models.CharField(default='', max_length=20, verbose_name='学院'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='college',
            field=models.CharField(default='', max_length=20, verbose_name='学院'),
        ),
    ]
