# Generated by Django 2.0.5 on 2018-06-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='publishTime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='发布时间'),
        ),
    ]
