# Generated by Django 2.0.5 on 2018-06-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingInfoNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('reform', '教改'), ('textbook', '教材'), ('research', '教研'), ('else', '其他')], max_length=10, verbose_name='项目分类')),
                ('title', models.CharField(default='', max_length=100, verbose_name='标题')),
                ('content', models.TextField(default='', max_length=500, verbose_name='内容')),
                ('fileUpload', models.FileField(default='', upload_to='fileUpload/%Y/%m')),
            ],
        ),
    ]
