# Generated by Django 2.0.5 on 2018-06-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachinginfonotification',
            name='publishTime',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='发布时间'),
        ),
    ]
