# Generated by Django 2.0.5 on 2018-06-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0003_auto_20180616_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingprojectapply',
            name='check_status',
            field=models.CharField(max_length=10, null=True, verbose_name='审核结果'),
        ),
    ]
