# Generated by Django 2.0.5 on 2018-06-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0004_auto_20180616_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachingprojectapply',
            name='check_status',
        ),
        migrations.AddField(
            model_name='teachingprojectapply',
            name='apply_status',
            field=models.CharField(max_length=10, null=True, verbose_name='申报审核结果'),
        ),
        migrations.AddField(
            model_name='teachingprojectapply',
            name='final_status',
            field=models.CharField(max_length=10, null=True, verbose_name='结题审核结果'),
        ),
        migrations.AddField(
            model_name='teachingprojectapply',
            name='medium_status',
            field=models.CharField(max_length=10, null=True, verbose_name='中期审核结果'),
        ),
    ]
