# Generated by Django 2.0.5 on 2018-06-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0008_auto_20180616_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachingprojectapply',
            name='verify_time',
        ),
        migrations.AddField(
            model_name='teachingprojectapply',
            name='apply_verify_time',
            field=models.DateField(blank=True, null=True, verbose_name='申报审核时间'),
        ),
        migrations.AddField(
            model_name='teachingprojectapply',
            name='final_verify_time',
            field=models.DateField(blank=True, null=True, verbose_name='结题审核时间'),
        ),
        migrations.AddField(
            model_name='teachingprojectapply',
            name='medium_verify_time',
            field=models.DateField(blank=True, null=True, verbose_name='中期审核时间'),
        ),
    ]
