# Generated by Django 2.0.5 on 2018-06-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0011_teachingprojectapply_extra_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitfile',
            name='file_name',
            field=models.CharField(default='', max_length=50, verbose_name='文件名'),
        ),
    ]
