# Generated by Django 2.0.5 on 2018-06-17 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0012_submitfile_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementsRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', max_length=500, verbose_name='成果具体记录')),
                ('record_time', models.DateField(auto_now_add=True, null=True, verbose_name='提交时间')),
                ('TPA_belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaching.TeachingProjectApply', verbose_name='所属项目')),
            ],
        ),
        migrations.CreateModel(
            name='FundsRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', max_length=500, verbose_name='使用经费具体记录')),
                ('record_time', models.DateField(auto_now_add=True, null=True, verbose_name='提交时间')),
                ('TPA_belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaching.TeachingProjectApply', verbose_name='所属项目')),
            ],
        ),
    ]
