# Generated by Django 2.0.5 on 2018-06-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0014_auto_20180617_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachinginfonotification',
            name='noticeType',
            field=models.CharField(default='teaching', max_length=10, verbose_name='通知类型'),
        ),
    ]
